version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:699630347910:task-definition/WINSPECT-SMETOOLKIT-FND-PROD-TASK"
        LoadBalancerInfo:
          ContainerName: "winspect-smetoolkit-frontend-prod"
          ContainerPort: 3000
        # Optional properties
        PlatformVersion: "LATEST"
        NetworkConfiguration:
          AwsvpcConfiguration:
            Subnets:
              [
                "subnet-07ad899b0ce5fbb28",
                "subnet-06fc29b57c75328f1",
                "subnet-0cd378a5a39a4e1aa",
              ]
            SecurityGroups: ["sg-03f7a6815f97b6ed9"]
            AssignPublicIp: "ENABLED"
